### ISSUE TITLE
Can't get plugin to work at all

### ISSUE THREAD

**Issue by lakemalcom** [jphalip/ideavim-peekaboo#1]
Hey, running IntelliJ IDEA 2024.1.3 (Build #IC-241.17890.1, built on June 3, 2024), installed your extension this morning, but I get nothing when hitting Ctrl-R or ". 

I've added `set peekaboo` to my ideavimrc and I've also tried just running `:set peekaboo` to no effect. Is there more set up that I'm missing? I know some plugins require additional commands to enable (like [this](https://github.com/JetBrains/ideavim/wiki/IdeaVim-Plugins)).

**Comment by lakemalcom** [comment]
I added `Plug 'ideavim-peekaboo'` to my ideavimrc and that seems to have made it work!

**Comment by jphalip** [comment]
Glad you got it to work! I'm not sure `Plug 'ideavim-peekaboo'` would do anything. Normally you should just need to add `set peekaboo` to your `~/ideavim.rc` and then source it or restart the IDE.
